<?php

namespace App\Models;

// use Illuminate\Contracts\Auth\MustVerifyEmail;
use Illuminate\Database\Eloquent\Factories\HasFactory;
use Illuminate\Foundation\Auth\User as Authenticatable;
use Illuminate\Notifications\Notifiable;
use Illuminate\Support\Str;
use Laravel\Sanctum\HasApiTokens; // --> Sanctum is Laravel's built in middleware so we don't need to build middleware manually like in express.js

class User extends Authenticatable
{
    /** @use HasFactory<\Database\Factories\UserFactory> */
    use HasApiTokens, HasFactory, Notifiable;

    protected $keyType = 'string';
    public $incrementing = false;
    
    /**
     * deleted because it's default laravel which is it will auto generated by laravel
     * protected $primaryKey = 'id';
     * public $timestamps = true;
     */
    
    protected $fillable = [
        'username',
        'password',
    ];

    protected $hidden = [
        'password',
    ];

    protected $casts = [
        'password' => 'hashed',
    ];

    /**
     * auto generate uuid prefix user-
     */
    protected static function booted(): void
    {
        static::creating(function($user) {
            if(empty($user->id)) {
                $user->id = (string) Str::uuid();
            }
        });
    }

    /**
     * relation: user has many articles
     */
    public function articles()
    {
        return $this->hasMany(Article::class);
    }
}